### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by jebyrnes** [MounaBelaid/covid19tunisia#3]
In the refresh function, I'm seeing calls to a few other functions - i.e., `average_data()` - but I don't see those in the package. Did you forget to commit utils.R or some other file?

**Comment by MounaBelaid** [comment]
Sorry I forget to delete these additional files. I have just updated the refresh file in the correct way so it just loads & returns the data. Thank you!

**Comment by jebyrnes** [comment]
Great!
