### ISSUE TITLE
refresh_covid19tunisia looking for objects that might not exist currently

### ISSUE THREAD

**Issue by jebyrnes** [MounaBelaid/covid19tunisia#4]
I suspect this is related to https://github.com/MounaBelaid/covid19tunisia/issues/3 and a file hasn't been committed/pushed or somesuch, but...

From the console - 
```
> library(covid19tunisia)
> dat <- refresh_covid19tunisia()
Error: glue cannot interpolate functions into strings.
* object 'url' is a function.
```

**Comment by MounaBelaid** [comment]
I have just fixed that. I include the utils.R file and edit the refresh file. Thank you for your support!

**Comment by jebyrnes** [comment]
Nice!
